#pragma once

// Generated by Legacy Crossplay Patcher. These defaults can also be edited
// manually before building console clients.
#ifndef CONSOLE_LEGACY_RELAY_ADDR_DEFAULT
#define CONSOLE_LEGACY_RELAY_ADDR_DEFAULT "127.0.0.1:61000"
#endif

#ifndef CONSOLE_LEGACY_RELAY_MODE_DEFAULT
#define CONSOLE_LEGACY_RELAY_MODE_DEFAULT "local"
#endif

#ifndef CONSOLE_LEGACY_RELAY_SESSION_DEFAULT
#define CONSOLE_LEGACY_RELAY_SESSION_DEFAULT "local-test"
#endif

#ifndef CONSOLE_LEGACY_RELAY_BUILD_DEFAULT
#define CONSOLE_LEGACY_RELAY_BUILD_DEFAULT "584111F7-1.0.10.0-lce1.2.3-net495-proto39"
#endif

#ifndef CONSOLE_LEGACY_RELAY_TOKEN_DEFAULT
#define CONSOLE_LEGACY_RELAY_TOKEN_DEFAULT ""
#endif
